# ------------------------------------------------------------------------------------ #
# Description:
#   Tests the deployment of the Function App.
#   
#
# Documentation:
#
# ------------------------------------------------------------------------------------ #

trigger: none

pool: DA-PBA

parameters:
- name: type
  displayName: Type of test
  type: string
  default: devops
  values:
  - devops
  - sndbx
 
variables:
- name: System.Debug
  value: true

- name: applicationInsightsName
  value: mneu-ai-dev-${{ parameters.type }}$(Build.BuildId)-049
  
- name: applicationInsightsResourceGroupName
  value: mneu-rg-dev-${{ parameters.type }}daresources-001

- name: applicationServicePlanName
  value: mneu-asp-dev-${{ parameters.type }}$(Build.BuildId)-049

- name: applicationServicePlanResourceGroupName
  value: mneu-rg-dev-${{ parameters.type }}daresources-001

- name: applicationServicePlanSize
  value: S1

- name: applicationServicePlanTier
  value: Standard

- name: connectedServiceName
  value: Infrastructure-As-Code-Dev

- name: functionAppName
  value: mneu-fap-${{ parameters.type }}$(Build.BuildId)-049

- name: resourceGroupName
  value: mneu-rg-dev-${{ parameters.type }}daresources-001

- name: storageAccountName
  value: mneusadev${{ parameters.type }}$(Build.BuildId)049

- name: storageAccountResourceGroupName
  value: mneu-rg-dev-${{ parameters.type }}daresources-001

- name: subscriptionID
  value: 775f881f-3b6b-45af-83e9-87e7b9b0bf01

jobs: 
- job: setup
  displayName: Setting up the template execution
  steps:
  - checkout: self
    path: paf

  - template: /resources/AA.ApplicationInsights/resource-template.yml@self
    parameters:
      applicationInsightsName: $(applicationInsightsName)
      connectedServiceName: $(connectedServiceName)
      resourceGroupName: $(applicationInsightsResourceGroupName)
      subscriptionID: $(subscriptionID)

  - template: /resources/AA.ApplicationServicePlan/resource-template.yml@self
    parameters:
      applicationServicePlanName: $(applicationServicePlanName)
      applicationServicePlanSize: $(applicationServicePlanSize)
      applicationServicePlanTier: $(applicationServicePlanTier)
      connectedServiceName: $(connectedServiceName)
      resourceGroupName: $(applicationServicePlanResourceGroupName)
      subscriptionID: $(subscriptionID)

  - template: /resources/AA.StorageAccount/resource-template.yml@self
    parameters:
      connectedServiceName: $(connectedServiceName)
      resourceGroupName: $(storageAccountResourceGroupName)
      storageAccountName: $(storageAccountName)
      subscriptionID: $(subscriptionID) 

- job: execute
  displayName: Executing the template
  condition: succeeded()
  dependsOn: setup
  steps:
  - checkout: self
    path: paf

  - template: /resources/AA.FunctionApp/resource-template.yml
    parameters:
      applicationInsightsResourceGroupName: $(applicationInsightsResourceGroupName)
      applicationInsightsName: $(applicationInsightsName)      
      applicationServicePlanName: $(applicationServicePlanName)   
      applicationServicePlanResourceGroupName: $(applicationServicePlanResourceGroupName)       
      connectedServiceName: $(connectedServiceName)      
      functionAppName: $(functionAppName) 
      resourceGroupName: $(resourceGroupName)
      storageAccountName: $(storageAccountName)
      storageAccountResourceGroupName: $(storageAccountResourceGroupName)
      subscriptionID: $(subscriptionID)

- ${{ if or(eq(parameters.type, 'devops'), ne(variables['Build.Reason'], 'Manual')) }}:
  - job: teardown
    displayName: Tearing down the template execution
    condition: always()
    dependsOn: tests
    steps:

    - template: /common/tools/AA.DeleteResources/delete-azure-resources.yml@self
      parameters:
        connectedServiceName: $(connectedServiceName)
        resources:
          - name: $(applicationServicePlanName)
            resourceGroupName: $(applicationServicePlanResourceGroupName)
            type: Microsoft.Web/serverfarms
          
          - name: $(applicationInsightsName)
            resourceGroupName: $(applicationInsightsResourceGroupName)
            type: Microsoft.Insights/components          
            
          - name: $(functionAppName)
            resourceGroupName: $(resourceGroupName)
            type: Microsoft.Web/functionApps
          
          - name: $(storageAccountName)
            resourceGroupName: $(storageAccountResourceGroupName)
            type: Microsoft.Storage/storageAccounts
          